version: "3.8"

services:
  ports_postgresql:
    image: postgres
    container_name: ports_postgresql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_ports=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ports_service
      - POSTGRES_HOST=5432
    command: -p 5432
  golang:
    container_name: ports_golang
    build: . 
    ports: 
    - "8000:8000"
